name: chatting_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  iconsax: ^0.0.8
  firebase_auth: ^4.2.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
font:
  family: Poppins
  fonts:
    - asset: assets/fonts/Poppins-Regular.ttf
    - asset: assets/fonts/Poppins-Medium.ttf
      weight: 500
    - asset: assets/fonts/Poppins-Bold.ttf
      weight: 700

