// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqh7wkX2UZgyvL3HJNUiE__yzGrFEcdsY',
    appId: '1:186767339963:web:059193bbb9676cd875549e',
    messagingSenderId: '186767339963',
    projectId: 'chating-app-b0155',
    authDomain: 'chating-app-b0155.firebaseapp.com',
    storageBucket: 'chating-app-b0155.appspot.com',
    measurementId: 'G-ZNHSXL0T4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkG3bEvX0KYVFriQhIxQNHKruI5Z4TjfE',
    appId: '1:186767339963:android:63c911b08d96bac175549e',
    messagingSenderId: '186767339963',
    projectId: 'chating-app-b0155',
    storageBucket: 'chating-app-b0155.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnmLaUqpe7r3l4x4e0po46W76kdZcyjTo',
    appId: '1:186767339963:ios:2324062aab07538375549e',
    messagingSenderId: '186767339963',
    projectId: 'chating-app-b0155',
    storageBucket: 'chating-app-b0155.appspot.com',
    iosClientId: '186767339963-69k5q9sa282o75kbl8m6vomvfom5g3nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnmLaUqpe7r3l4x4e0po46W76kdZcyjTo',
    appId: '1:186767339963:ios:2324062aab07538375549e',
    messagingSenderId: '186767339963',
    projectId: 'chating-app-b0155',
    storageBucket: 'chating-app-b0155.appspot.com',
    iosClientId: '186767339963-69k5q9sa282o75kbl8m6vomvfom5g3nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
